name: code-deploy
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: "Cloning the code"
        uses: actions/checkout@v6
      - name: "Install the dependencies"
        run: npm ci
      - name: "Lint Code"
        run: npm run lint
      - name: "Run Tests"
        run: npm test
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: "Cloning the code"
        uses: actions/checkout@v6
      - name: "Install the dependencies"
        run: npm ci
      - name: "Building the code"
        run: npm run build
      - name: "Uploading artifacts"
        uses: actions/upload-artifact@v4
        with:
          name: "Dist files"
          path: | # where to find the artefacts after the execution of jobs
            dist
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: "Deploy the code"
        run: echo "Deploying"
